# Generated by Django 4.0.3 on 2022-03-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receitas_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
