# Generated by Django 4.0.3 on 2022-04-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receitas_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
